edit_mode = "vi"
history_size = 1000000000
path = ["/home/matt/.cargo/bin", "/home/matt/development/go-workspace/bin"]
startup = [
	"alias la [path] { exa -la $path }",
	"alias vim [el] { nvim $el }"
]

[env]
LANG = "en_US.UTF-8"
STARSHIP_CONFIG = "/home/matt/.config/starship/config.toml"
GPG_TTY = "/dev/pts/0"
